### ISSUE TITLE
load data from cache alway

### ISSUE THREAD

**Issue by zw277856645** [PillowPillow/ng2-webstorage#107] opened 2019-05-10 11:00 UTC
**Versions (please complete the following information):**
 - NgxWebstorage: [e.g. 3.0.x]
 - Angular: [e.g. 7.2.0]

**Describe the bug**
step 1: let data = localStorageService.retrieve(key) to get data, which is object data
step 2: change something in data, like data.name = 'xxx'
step 3: localStorageService.store(key, data) 
step 4: call  let data = localStorageService.retrieve(key)  again

then bug appear, data is load from cache, not the new data stored after change.

Can you provide config to disable the cache? or you can fix this bug

**Comment by PillowPillow** [comment] 2019-05-10 12:58
Hello, I m unable to reproduce your issue. I tried with the sandbox with the [following code](https://github.com/PillowPillow/ng2-webstorage/blob/1deb83a90c90f98dc7ba7c16a45d6184d406e3bf/src/app/_components/appForm/appForm.ts#L37) and it works as described in the readme.

Can you provide me the exact code that your are using or an example (on stackblitz, github .. ) ?

**Comment by PillowPillow** [comment] 2019-06-03 12:45
no news after 1 month, closing this issue. Feel free to open another issue if needed.

**Closed by PillowPillow** 2019-06-03 12:45 UTC

**Comment by rsivan** [comment] 2021-01-12 22:30
I am noticing a similar issue on 6.0.0.
Will soon retest on 7.x

**Comment by rsivan** [comment] 2021-02-01 17:08
Just updated to 7.0.1, still getting results from cache after logout-login (I verified the Application tab session storage is indeed cleared)
