### ISSUE TITLE
Decorators invoked before `Ng2Webstorage.forRoot` sets prefix/separator

### ISSUE THREAD

**Issue by ross-nordstrom** [PillowPillow/ng2-webstorage#83] opened 2018-01-03 04:11 UTC
When I upgraded from 1.8.0 to 2.0.1, my storage is lost when I reopen my app in a new tab.  When I set some breakpoints, it looks like this is because the decorators (`@LocalStorage`, `@SessionStorage`) are getting invoked (`decorators/webStorage.js`) before my config is set (`interfaces/config`).

I've got a multi-module application, and I'm setting `forRoot({prefix: 'foo', separator: '/', caseSensitive: false})` in my CoreModule, which is imported and used by all other modules.

Any ideas?   This worked fine for us in 1.8.0
  

Relevant libs:
```js
    "@angular/cli": "1.6.3",
    "@angular/core": "5.1.2", // same for @angular/*
    "@angular/material": "5.0.2",
    "ngx-webstorage": "2.0.1",
```

**Comment by PillowPillow** [comment] 2018-01-03 14:51
Hi, @ross-nordstrom , the behavior that you described totally normal. Even if the decorator triggers before the configuration, [their executions delayed until the app initialization](https://github.com/PillowPillow/ng2-webstorage/blob/81f4d25c997bb898473aacb28ad7b1e03b6ef41f/lib/decorators/webStorage.ts#L26).
I added this behav to fix the configuration usage with decorator with v2.0.0. (issue #55)

On the other hand, i m using the library this way and it works like a charm.

You said that your CoreModule contains the forRoot call, how did you declare your module exactly? The bug could come from a multiple instanciation of the Ng2Webstorage. 
Personnaly, to avoid any error i'm calling every configurations from my main module (app generally) and i declare in the shared one only the base modules (do not call the forRoot or whatever name for module init method). 

Without more information i can't rellay help you since i can't reproduce the issue from my side. 
Maybe you could try to clear the localstorage and reload your application seeing if their is any ng2-webstorage|xxxx variables stored. 

regards

**Comment by PillowPillow** [comment] 2018-01-19 12:44
I'm closing this issue since there isn't any news since more than 15days. Feel free to open another if you still encounter this issue.

**Closed by PillowPillow** 2018-01-19 12:44 UTC
